#version 450

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(binding = 0, r32f) uniform writeonly image2D HIzMip;
layout(binding = 1) uniform sampler2D depth;

layout(push_constant) uniform block
{
	vec2 imageSize;
};

void main()
{
	uvec2 pos = gl_GlobalInvocationID.xy;
	float depth = texture(depth, (vec2(pos) + vec2(0.5)) / imageSize).x;

	imageStore(HIzMip, ivec2(pos), vec4(depth));
}
